/* Generated by refresh-snapshot.mjs; non-sensitive local Admin snapshot. */
window.MODEL_COST_SNAPSHOT = {
  "meta": {
    "observedAt": "2026-09-30 13:18:33 Asia/Shanghai",
    "database": "dramastudio_local",
    "source": "本机 studio_channel / studio_channel_model / studio_billing_template（只读快照）",
    "note": "不含 API Key、凭证、余额与任何用户数据。金额字段按仓库约定为分，展示时换算为元。"
  },
  "stats": {
    "channels": 14,
    "models": 72,
    "enabledModels": 70,
    "abilityRows": 90,
    "excludedAbilityRows": 6
  },
  "channels": [
    {
      "id": 21,
      "name": "火山方舟",
      "platform": "火山方舟",
      "region": "domestic"
    },
    {
      "id": 23,
      "name": "火山 MediaKit",
      "platform": "火山引擎 MediaKit",
      "region": "domestic"
    },
    {
      "id": 24,
      "name": "BytePlus ModelArk 新加坡",
      "platform": "BytePlus ModelArk",
      "region": "overseas"
    },
    {
      "id": 25,
      "name": "Kling AI Global - release-overseas",
      "platform": "Kling AI Global",
      "region": "overseas"
    },
    {
      "id": 27,
      "name": "Google Vertex AI - release-overseas",
      "platform": "Google Cloud Vertex AI",
      "region": "overseas"
    },
    {
      "id": 28,
      "name": "火山引擎豆包语音 Seed Audio",
      "platform": "火山引擎豆包语音",
      "region": "domestic"
    },
    {
      "id": 30,
      "name": "BytePlus Voice 新加坡（Seed Audio 1.0 / TTS 2.0）",
      "platform": "BytePlus Voice",
      "region": "overseas"
    },
    {
      "id": 31,
      "name": "MiniMax Global",
      "platform": "MiniMax API Platform",
      "region": "overseas"
    },
    {
      "id": 32,
      "name": "Black Forest Labs · FLUX.2 (Default)",
      "platform": "Black Forest Labs API",
      "region": "overseas"
    },
    {
      "id": 35,
      "name": "xAI（Grok Imagine 图片 / 视频）",
      "platform": "xAI API",
      "region": "overseas"
    },
    {
      "id": 36,
      "name": "百度智能云（大模型语音合成）",
      "platform": "百度智能云语音",
      "region": "domestic"
    },
    {
      "id": 37,
      "name": "百度智能云·千帆文本",
      "platform": "百度智能云千帆",
      "region": "domestic"
    },
    {
      "id": 38,
      "name": "Alibaba Model Studio SG",
      "platform": "Alibaba Cloud Model Studio",
      "region": "overseas"
    },
    {
      "id": 39,
      "name": "BytePlus AI MediaKit 新加坡",
      "platform": "BytePlus AI MediaKit",
      "region": "overseas"
    }
  ],
  "models": [
    {
      "id": "21:doubao-seedream-5-0-pro-260628",
      "channelId": 21,
      "channel": "火山方舟",
      "channelPlatform": "火山方舟",
      "region": "domestic",
      "model": "doubao-seedream-5-0-pro-260628",
      "upstreamModel": "doubao-seedream-5-0-pro-260628",
      "name": "Seedream 5.0 Pro",
      "maker": "字节跳动 / ByteDance",
      "modality": "image",
      "catalogCard": "火山·Seedream",
      "templateId": 19,
      "templateName": "火山方舟 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 109,
          "category": "text2image",
          "label": "文生图",
          "protocol": "ark-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 30,
                "sale": 60
              }
            }
          }
        },
        {
          "id": 120,
          "category": "image2image",
          "label": "参考图生图",
          "protocol": "ark-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 50,
                "sale": 100
              }
            }
          }
        },
        {
          "id": 126,
          "category": "image_repaint",
          "label": "图片重绘",
          "protocol": "ark-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 50,
                "sale": 100
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "21:doubao-seedream-5-0-260128",
      "channelId": 21,
      "channel": "火山方舟",
      "channelPlatform": "火山方舟",
      "region": "domestic",
      "model": "doubao-seedream-5-0-260128",
      "upstreamModel": "doubao-seedream-5-0-260128",
      "name": "Seedream 5.0 lite",
      "maker": "字节跳动 / ByteDance",
      "modality": "image",
      "catalogCard": "火山·Seedream",
      "templateId": 19,
      "templateName": "火山方舟 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 110,
          "category": "text2image",
          "label": "文生图",
          "protocol": "ark-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 22,
                "sale": 44
              }
            }
          }
        },
        {
          "id": 121,
          "category": "image2image",
          "label": "参考图生图",
          "protocol": "ark-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 22,
                "sale": 44
              }
            }
          }
        },
        {
          "id": 127,
          "category": "image_repaint",
          "label": "图片重绘",
          "protocol": "ark-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 22,
                "sale": 44
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "21:doubao-seedream-4-5-251128",
      "channelId": 21,
      "channel": "火山方舟",
      "channelPlatform": "火山方舟",
      "region": "domestic",
      "model": "doubao-seedream-4-5-251128",
      "upstreamModel": "doubao-seedream-4-5-251128",
      "name": "Seedream 4.5",
      "maker": "字节跳动 / ByteDance",
      "modality": "image",
      "catalogCard": "火山·Seedream",
      "templateId": 19,
      "templateName": "火山方舟 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 111,
          "category": "text2image",
          "label": "文生图",
          "protocol": "ark-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 25,
                "sale": 50
              }
            }
          }
        },
        {
          "id": 122,
          "category": "image2image",
          "label": "参考图生图",
          "protocol": "ark-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 25,
                "sale": 50
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "21:doubao-seedream-4-0-250828",
      "channelId": 21,
      "channel": "火山方舟",
      "channelPlatform": "火山方舟",
      "region": "domestic",
      "model": "doubao-seedream-4-0-250828",
      "upstreamModel": "doubao-seedream-4-0-250828",
      "name": "Seedream 4.0",
      "maker": "字节跳动 / ByteDance",
      "modality": "image",
      "catalogCard": "火山·Seedream",
      "templateId": 19,
      "templateName": "火山方舟 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 112,
          "category": "text2image",
          "label": "文生图",
          "protocol": "ark-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 20,
                "sale": 40
              }
            }
          }
        },
        {
          "id": 123,
          "category": "image2image",
          "label": "参考图生图",
          "protocol": "ark-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 20,
                "sale": 40
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "21:doubao-seedance-2-0-260128",
      "channelId": 21,
      "channel": "火山方舟",
      "channelPlatform": "火山方舟",
      "region": "domestic",
      "model": "doubao-seedance-2-0-260128",
      "upstreamModel": "doubao-seedance-2-0-260128",
      "name": "Seedance 2.0",
      "maker": "字节跳动 / ByteDance",
      "modality": "video",
      "catalogCard": "火山·Seedance 2.0",
      "templateId": 19,
      "templateName": "火山方舟 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 113,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "ark-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "4K": {
                "cost": 505,
                "sale": 1010,
                "inCost": 415,
                "inSale": 830
              },
              "480P": {
                "cost": 46,
                "sale": 92,
                "inCost": 38,
                "inSale": 76
              },
              "720P": {
                "cost": 99,
                "sale": 198,
                "inCost": 81,
                "inSale": 162
              },
              "1080P": {
                "cost": 248,
                "sale": 496,
                "inCost": 201,
                "inSale": 402
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "21:doubao-seedance-2-0-fast-260128",
      "channelId": 21,
      "channel": "火山方舟",
      "channelPlatform": "火山方舟",
      "region": "domestic",
      "model": "doubao-seedance-2-0-fast-260128",
      "upstreamModel": "doubao-seedance-2-0-fast-260128",
      "name": "Seedance 2.0 Fast",
      "maker": "字节跳动 / ByteDance",
      "modality": "video",
      "catalogCard": "火山·Seedance 2.0 Fast",
      "templateId": 19,
      "templateName": "火山方舟 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 114,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "ark-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "480P": {
                "cost": 37,
                "sale": 74,
                "inCost": 30,
                "inSale": 60
              },
              "720P": {
                "cost": 80,
                "sale": 160,
                "inCost": 64,
                "inSale": 128
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "21:doubao-seed-2-1-pro-260628",
      "channelId": 21,
      "channel": "火山方舟",
      "channelPlatform": "火山方舟",
      "region": "domestic",
      "model": "doubao-seed-2-1-pro-260628",
      "upstreamModel": "doubao-seed-2-1-pro-260628",
      "name": "Doubao Seed 2.1 Pro",
      "maker": "字节跳动 / ByteDance",
      "modality": "text",
      "catalogCard": "火山·豆包（多模态）",
      "templateId": 19,
      "templateName": "火山方舟 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 115,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 600,
            "saleIn": 1200,
            "costOut": 3000,
            "saleOut": 6000
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "21:doubao-seed-2-1-turbo-260628",
      "channelId": 21,
      "channel": "火山方舟",
      "channelPlatform": "火山方舟",
      "region": "domestic",
      "model": "doubao-seed-2-1-turbo-260628",
      "upstreamModel": "doubao-seed-2-1-turbo-260628",
      "name": "Doubao Seed 2.1 Turbo",
      "maker": "字节跳动 / ByteDance",
      "modality": "text",
      "catalogCard": "火山·豆包（多模态）",
      "templateId": 19,
      "templateName": "火山方舟 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 116,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 300,
            "saleIn": 600,
            "costOut": 1500,
            "saleOut": 3000
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "21:doubao-seed-2-0-pro-260215",
      "channelId": 21,
      "channel": "火山方舟",
      "channelPlatform": "火山方舟",
      "region": "domestic",
      "model": "doubao-seed-2-0-pro-260215",
      "upstreamModel": "doubao-seed-2-0-pro-260215",
      "name": "Doubao Seed 2.0 Pro",
      "maker": "字节跳动 / ByteDance",
      "modality": "text",
      "catalogCard": "火山·豆包（多模态）",
      "templateId": 19,
      "templateName": "火山方舟 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 117,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": false,
          "price": {
            "mode": "token",
            "costIn": 960,
            "saleIn": 1920,
            "costOut": 4800,
            "saleOut": 9600
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": false,
      "pricingComplete": true
    },
    {
      "id": "21:doubao-seed-2-0-mini-260428",
      "channelId": 21,
      "channel": "火山方舟",
      "channelPlatform": "火山方舟",
      "region": "domestic",
      "model": "doubao-seed-2-0-mini-260428",
      "upstreamModel": "doubao-seed-2-0-mini-260428",
      "name": "Doubao Seed 2.0 Mini",
      "maker": "字节跳动 / ByteDance",
      "modality": "text",
      "catalogCard": "火山·豆包（多模态）",
      "templateId": 19,
      "templateName": "火山方舟 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 118,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": false,
          "price": {
            "mode": "token",
            "costIn": 80,
            "saleIn": 160,
            "costOut": 800,
            "saleOut": 1600
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": false,
      "pricingComplete": true
    },
    {
      "id": "21:doubao-seed-2-0-lite-260428",
      "channelId": 21,
      "channel": "火山方舟",
      "channelPlatform": "火山方舟",
      "region": "domestic",
      "model": "doubao-seed-2-0-lite-260428",
      "upstreamModel": "doubao-seed-2-0-lite-260428",
      "name": "Doubao Seed 2.0 Lite",
      "maker": "字节跳动 / ByteDance",
      "modality": "text",
      "catalogCard": "火山·豆包（多模态）",
      "templateId": 19,
      "templateName": "火山方舟 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 119,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 180,
            "saleIn": 360,
            "costOut": 1080,
            "saleOut": 2160
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "23:volc-mediakit",
      "channelId": 23,
      "channel": "火山 MediaKit",
      "channelPlatform": "火山引擎 MediaKit",
      "region": "domestic",
      "model": "volc-mediakit",
      "upstreamModel": "volc-mediakit",
      "name": "火山 MediaKit 图片处理",
      "maker": "字节跳动 / ByteDance",
      "modality": "image",
      "catalogCard": "火山·MediaKit（图片）",
      "templateId": 0,
      "templateName": "",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 128,
          "category": "image_func",
          "label": "图片工具",
          "protocol": "volc-mediakit",
          "enabled": true,
          "price": {
            "mode": "functions",
            "items": {
              "扩图#2": {
                "cost": 4,
                "sale": 8
              },
              "抠图#1": {
                "cost": 1,
                "sale": 2
              },
              "去水印#0": {
                "cost": 1,
                "sale": 2
              },
              "图片高清#3": {
                "cost": 4,
                "sale": 8
              }
            }
          }
        },
        {
          "id": 129,
          "category": "video_func",
          "label": "视频工具",
          "protocol": "volc-mediakit",
          "enabled": true,
          "price": {
            "mode": "functions",
            "items": {
              "人声分离#7": {
                "cost": 7,
                "sale": 14
              },
              "剧本还原#4": {
                "cost": 300,
                "sale": 600
              },
              "字幕擦除#6": {
                "cost": 100,
                "sale": 200
              },
              "视频高清·专业#1": {
                "cost": 24000,
                "sale": 48000
              },
              "视频高清·极速#2": {
                "cost": 640,
                "sale": 1280
              },
              "视频高清·标准#0": {
                "cost": 2400,
                "sale": 4800
              },
              "剧情故事线分析#5": {
                "cost": 100,
                "sale": 200
              },
              "视频高清·大模型#3": {
                "cost": 4000,
                "sale": 8000
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-seedance-1-0-pro-fast-251015",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-seedance-1-0-pro-fast-251015",
      "upstreamModel": "seedance-1-0-pro-fast-251015",
      "name": "ByteDance Seedance 1.0 Pro Fast",
      "maker": "字节跳动 / ByteDance",
      "modality": "video",
      "catalogCard": "BytePlus·Seedance 1.0 Pro Fast",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 130,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "ark-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "480P": {
                "cost": 8,
                "sale": 16,
                "inCost": 0,
                "inSale": 0
              },
              "720P": {
                "cost": 17,
                "sale": 34,
                "inCost": 0,
                "inSale": 0
              },
              "1080P": {
                "cost": 35,
                "sale": 70,
                "inCost": 0,
                "inSale": 0
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-seedance-1-5-pro-251215",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-seedance-1-5-pro-251215",
      "upstreamModel": "seedance-1-5-pro-251215",
      "name": "ByteDance Seedance 1.5 Pro",
      "maker": "字节跳动 / ByteDance",
      "modality": "video",
      "catalogCard": "BytePlus·Seedance 1.5 Pro",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 131,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "ark-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "480P": {
                "cost": 18,
                "sale": 36,
                "inCost": 0,
                "inSale": 0
              },
              "720P": {
                "cost": 38,
                "sale": 76,
                "inCost": 0,
                "inSale": 0
              },
              "1080P": {
                "cost": 83,
                "sale": 166,
                "inCost": 0,
                "inSale": 0
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-dreamina-seedance-2-0-mini-260615",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-dreamina-seedance-2-0-mini-260615",
      "upstreamModel": "dreamina-seedance-2-0-mini-260615",
      "name": "Dreamina Seedance 2.0 Mini",
      "maker": "字节跳动 / ByteDance",
      "modality": "video",
      "catalogCard": "BytePlus·Dreamina Seedance 2.0 Mini",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 134,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "ark-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "480P": {
                "cost": 29,
                "sale": 58,
                "inCost": 20,
                "inSale": 40
              },
              "720P": {
                "cost": 58,
                "sale": 116,
                "inCost": 43,
                "inSale": 86
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-glm-5-3-flash-260828",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-glm-5-3-flash-260828",
      "upstreamModel": "glm-5-3-flash-260828",
      "name": "GLM 5.3 Flash",
      "maker": "智谱 AI（经 BytePlus）",
      "modality": "text",
      "catalogCard": "BytePlus·ModelArk 文本",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 174,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 108,
            "saleIn": 216,
            "costOut": 357,
            "saleOut": 714
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-deepseek-v4-pro-ga-260813",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-deepseek-v4-pro-ga-260813",
      "upstreamModel": "deepseek-v4-pro-ga-260813",
      "name": "DeepSeek V4 Pro GA",
      "maker": "DeepSeek（经 BytePlus）",
      "modality": "text",
      "catalogCard": "BytePlus·ModelArk 文本",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 175,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 943,
            "saleIn": 1886,
            "costOut": 2828,
            "saleOut": 5656
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-deepseek-v4-flash-ga-260731",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-deepseek-v4-flash-ga-260731",
      "upstreamModel": "deepseek-v4-flash-ga-260731",
      "name": "DeepSeek V4 Flash GA",
      "maker": "DeepSeek（经 BytePlus）",
      "modality": "text",
      "catalogCard": "BytePlus·ModelArk 文本",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 176,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 315,
            "saleIn": 630,
            "costOut": 943,
            "saleOut": 1886
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-dola-seed-2-1-turbo-260628",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-dola-seed-2-1-turbo-260628",
      "upstreamModel": "dola-seed-2-1-turbo-260628",
      "name": "Dola Seed 2.1 Turbo",
      "maker": "字节跳动 / ByteDance",
      "modality": "text",
      "catalogCard": "BytePlus·ModelArk 文本",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 177,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 357,
            "saleIn": 714,
            "costOut": 1785,
            "saleOut": 3570
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-glm-5-2-260617",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-glm-5-2-260617",
      "upstreamModel": "glm-5-2-260617",
      "name": "GLM 5.2",
      "maker": "智谱 AI（经 BytePlus）",
      "modality": "text",
      "catalogCard": "BytePlus·ModelArk 文本",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 178,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 1000,
            "saleIn": 2000,
            "costOut": 3142,
            "saleOut": 6284
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-seed-2-0-mini-260428",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-seed-2-0-mini-260428",
      "upstreamModel": "seed-2-0-mini-260428",
      "name": "Dola Seed 2.0 Mini",
      "maker": "字节跳动 / ByteDance",
      "modality": "text",
      "catalogCard": "BytePlus·ModelArk 文本",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 179,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 143,
            "saleIn": 286,
            "costOut": 572,
            "saleOut": 1144
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-seed-2-0-lite-260428",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-seed-2-0-lite-260428",
      "upstreamModel": "seed-2-0-lite-260428",
      "name": "Dola Seed 2.0 Lite",
      "maker": "字节跳动 / ByteDance",
      "modality": "text",
      "catalogCard": "BytePlus·ModelArk 文本",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 180,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 357,
            "saleIn": 714,
            "costOut": 2856,
            "saleOut": 5712
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-deepseek-v4-flash-260425",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-deepseek-v4-flash-260425",
      "upstreamModel": "deepseek-v4-flash-260425",
      "name": "DeepSeek V4 Flash",
      "maker": "DeepSeek（经 BytePlus）",
      "modality": "text",
      "catalogCard": "BytePlus·ModelArk 文本",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 181,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 315,
            "saleIn": 630,
            "costOut": 943,
            "saleOut": 1886
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-deepseek-v4-pro-260425",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-deepseek-v4-pro-260425",
      "upstreamModel": "deepseek-v4-pro-260425",
      "name": "DeepSeek V4 Pro",
      "maker": "DeepSeek（经 BytePlus）",
      "modality": "text",
      "catalogCard": "BytePlus·ModelArk 文本",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 182,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 943,
            "saleIn": 1886,
            "costOut": 2828,
            "saleOut": 5656
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-seed-2-0-code-preview-260328",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-seed-2-0-code-preview-260328",
      "upstreamModel": "seed-2-0-code-preview-260328",
      "name": "Dola Seed 2.0 Code",
      "maker": "字节跳动 / ByteDance",
      "modality": "text",
      "catalogCard": "BytePlus·ModelArk 文本",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 183,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 714,
            "saleIn": 1428,
            "costOut": 4284,
            "saleOut": 8568
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-seed-2-0-pro-260328",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-seed-2-0-pro-260328",
      "upstreamModel": "seed-2-0-pro-260328",
      "name": "Dola Seed 2.0 Pro",
      "maker": "字节跳动 / ByteDance",
      "modality": "text",
      "catalogCard": "BytePlus·ModelArk 文本",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 184,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 714,
            "saleIn": 1428,
            "costOut": 4284,
            "saleOut": 8568
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-glm-4-7-251222",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-glm-4-7-251222",
      "upstreamModel": "glm-4-7-251222",
      "name": "GLM 4.7",
      "maker": "智谱 AI（经 BytePlus）",
      "modality": "text",
      "catalogCard": "BytePlus·ModelArk 文本",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 185,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 429,
            "saleIn": 858,
            "costOut": 1571,
            "saleOut": 3142
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-seed-1-8-251228",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-seed-1-8-251228",
      "upstreamModel": "seed-1-8-251228",
      "name": "ByteDance Seed 1.8",
      "maker": "字节跳动 / ByteDance",
      "modality": "text",
      "catalogCard": "BytePlus·ModelArk 文本",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 186,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 357,
            "saleIn": 714,
            "costOut": 2856,
            "saleOut": 5712
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-deepseek-v3-2-251201",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-deepseek-v3-2-251201",
      "upstreamModel": "deepseek-v3-2-251201",
      "name": "DeepSeek V3.2",
      "maker": "DeepSeek（经 BytePlus）",
      "modality": "text",
      "catalogCard": "BytePlus·ModelArk 文本",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 187,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 400,
            "saleIn": 800,
            "costOut": 600,
            "saleOut": 1200
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-seed-1-6-250915",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-seed-1-6-250915",
      "upstreamModel": "seed-1-6-250915",
      "name": "ByteDance Seed 1.6",
      "maker": "字节跳动 / ByteDance",
      "modality": "text",
      "catalogCard": "BytePlus·ModelArk 文本",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 188,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 357,
            "saleIn": 714,
            "costOut": 2856,
            "saleOut": 5712
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-seed-1-6-flash-250715",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-seed-1-6-flash-250715",
      "upstreamModel": "seed-1-6-flash-250715",
      "name": "ByteDance Seed 1.6 Flash",
      "maker": "字节跳动 / ByteDance",
      "modality": "text",
      "catalogCard": "BytePlus·ModelArk 文本",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 189,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "openai-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 72,
            "saleIn": 144,
            "costOut": 572,
            "saleOut": 1144
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-dreamina-seedance-2-5-260628",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-dreamina-seedance-2-5-260628",
      "upstreamModel": "dreamina-seedance-2-5-260628",
      "name": "Dreamina Seedance 2.5",
      "maker": "字节跳动 / ByteDance",
      "modality": "video",
      "catalogCard": "BytePlus·Dreamina Seedance 2.5",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 205,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "ark-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "480P": {
                "cost": 75,
                "sale": 150,
                "inCost": 57,
                "inSale": 114
              },
              "720P": {
                "cost": 167,
                "sale": 334,
                "inCost": 128,
                "inSale": 256
              },
              "1080P": {
                "cost": 410,
                "sale": 820,
                "inCost": 315,
                "inSale": 630
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-29 17:09:25",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-dreamina-seedance-2-0-260128",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-dreamina-seedance-2-0-260128",
      "upstreamModel": "dreamina-seedance-2-0-260128",
      "name": "Dreamina Seedance 2.0",
      "maker": "字节跳动 / ByteDance",
      "modality": "video",
      "catalogCard": "BytePlus·Dreamina Seedance 2.0",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 206,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "ark-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "4K": {
                "cost": 562,
                "sale": 1124,
                "inCost": 432,
                "inSale": 864
              },
              "480P": {
                "cost": 51,
                "sale": 102,
                "inCost": 41,
                "inSale": 82
              },
              "720P": {
                "cost": 108,
                "sale": 216,
                "inCost": 87,
                "inSale": 174
              },
              "1080P": {
                "cost": 267,
                "sale": 534,
                "inCost": 212,
                "inSale": 424
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-29 17:10:19",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "24:byteplus-dreamina-seedance-2-0-fast-260128",
      "channelId": 24,
      "channel": "BytePlus ModelArk 新加坡",
      "channelPlatform": "BytePlus ModelArk",
      "region": "overseas",
      "model": "byteplus-dreamina-seedance-2-0-fast-260128",
      "upstreamModel": "dreamina-seedance-2-0-fast-260128",
      "name": "Dreamina Seedance 2.0 Fast",
      "maker": "字节跳动 / ByteDance",
      "modality": "video",
      "catalogCard": "BytePlus·Dreamina Seedance 2.0 Fast",
      "templateId": 20,
      "templateName": "BytePlus ModelArk 新加坡 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 207,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "ark-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "480P": {
                "cost": 44,
                "sale": 88,
                "inCost": 31,
                "inSale": 62
              },
              "720P": {
                "cost": 87,
                "sale": 174,
                "inCost": 66,
                "inSale": 132
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-29 17:11:12",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "25:kling-global-video-v3-omni",
      "channelId": 25,
      "channel": "Kling AI Global - release-overseas",
      "channelPlatform": "Kling AI Global",
      "region": "overseas",
      "model": "kling-global-video-v3-omni",
      "upstreamModel": "kling-v3-omni",
      "name": "Kling 3.0 Omni (Global)",
      "maker": "快手 · 可灵 AI",
      "modality": "video",
      "catalogCard": "Kling AI Global·3.0/Omni",
      "templateId": 21,
      "templateName": "Kling AI Global - release-overseas 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 132,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "kling-v1-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "4K": {
                "cost": 300,
                "sale": 600,
                "inCost": 300,
                "inSale": 600
              },
              "720P": {
                "cost": 80,
                "sale": 160,
                "inCost": 90,
                "inSale": 180
              },
              "1080P": {
                "cost": 100,
                "sale": 200,
                "inCost": 120,
                "inSale": 240
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "25:kling-global-video-v3",
      "channelId": 25,
      "channel": "Kling AI Global - release-overseas",
      "channelPlatform": "Kling AI Global",
      "region": "overseas",
      "model": "kling-global-video-v3",
      "upstreamModel": "kling-v3",
      "name": "Kling 3.0 (Global)",
      "maker": "快手 · 可灵 AI",
      "modality": "video",
      "catalogCard": "Kling AI Global·3.0/Omni",
      "templateId": 21,
      "templateName": "Kling AI Global - release-overseas 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 133,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "kling-v1-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "4K": {
                "cost": 300,
                "sale": 600,
                "inCost": 0,
                "inSale": 0
              },
              "720P": {
                "cost": 90,
                "sale": 180,
                "inCost": 0,
                "inSale": 0
              },
              "1080P": {
                "cost": 120,
                "sale": 240,
                "inCost": 0,
                "inSale": 0
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "27:gemini-3-pro-image",
      "channelId": 27,
      "channel": "Google Vertex AI - release-overseas",
      "channelPlatform": "Google Cloud Vertex AI",
      "region": "overseas",
      "model": "gemini-3-pro-image",
      "upstreamModel": "gemini-3-pro-image",
      "name": "Nano Banana Pro",
      "maker": "Google",
      "modality": "image",
      "catalogCard": "Vertex AI·NanoBanana",
      "templateId": 23,
      "templateName": "Google Vertex AI - release-overseas 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 141,
          "category": "text2image",
          "label": "文生图",
          "protocol": "vertex-gemini",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "1K": {
                "cost": 96,
                "sale": 192
              },
              "2K": {
                "cost": 96,
                "sale": 192
              },
              "4K": {
                "cost": 172,
                "sale": 344
              },
              "base_request": {
                "cost": 1,
                "sale": 2
              }
            }
          }
        },
        {
          "id": 142,
          "category": "image2image",
          "label": "参考图生图",
          "protocol": "vertex-gemini",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "1K": {
                "cost": 96,
                "sale": 192
              },
              "2K": {
                "cost": 96,
                "sale": 192
              },
              "4K": {
                "cost": 172,
                "sale": 344
              },
              "input_image": {
                "cost": 1,
                "sale": 2
              },
              "base_request": {
                "cost": 1,
                "sale": 2
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "27:gemini-3.1-flash-image",
      "channelId": 27,
      "channel": "Google Vertex AI - release-overseas",
      "channelPlatform": "Google Cloud Vertex AI",
      "region": "overseas",
      "model": "gemini-3.1-flash-image",
      "upstreamModel": "gemini-3.1-flash-image",
      "name": "Nano Banana 2",
      "maker": "Google",
      "modality": "image",
      "catalogCard": "Vertex AI·NanoBanana",
      "templateId": 23,
      "templateName": "Google Vertex AI - release-overseas 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 143,
          "category": "text2image",
          "label": "文生图",
          "protocol": "vertex-gemini",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "512": {
                "cost": 33,
                "sale": 66
              },
              "1K": {
                "cost": 48,
                "sale": 96
              },
              "2K": {
                "cost": 73,
                "sale": 146
              },
              "4K": {
                "cost": 108,
                "sale": 216
              },
              "base_request": {
                "cost": 1,
                "sale": 2
              }
            }
          }
        },
        {
          "id": 144,
          "category": "image2image",
          "label": "参考图生图",
          "protocol": "vertex-gemini",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "512": {
                "cost": 33,
                "sale": 66
              },
              "1K": {
                "cost": 48,
                "sale": 96
              },
              "2K": {
                "cost": 73,
                "sale": 146
              },
              "4K": {
                "cost": 108,
                "sale": 216
              },
              "input_image": {
                "cost": 1,
                "sale": 2
              },
              "base_request": {
                "cost": 1,
                "sale": 2
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "27:gemini-3.1-flash-lite-image",
      "channelId": 27,
      "channel": "Google Vertex AI - release-overseas",
      "channelPlatform": "Google Cloud Vertex AI",
      "region": "overseas",
      "model": "gemini-3.1-flash-lite-image",
      "upstreamModel": "gemini-3.1-flash-lite-image",
      "name": "Nano Banana 2 Lite",
      "maker": "Google",
      "modality": "image",
      "catalogCard": "Vertex AI·NanoBanana",
      "templateId": 23,
      "templateName": "Google Vertex AI - release-overseas 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 145,
          "category": "text2image",
          "label": "文生图",
          "protocol": "vertex-gemini",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "1K": {
                "cost": 25,
                "sale": 50
              },
              "base_request": {
                "cost": 1,
                "sale": 2
              }
            }
          }
        },
        {
          "id": 146,
          "category": "image2image",
          "label": "参考图生图",
          "protocol": "vertex-gemini",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "1K": {
                "cost": 25,
                "sale": 50
              },
              "input_image": {
                "cost": 1,
                "sale": 2
              },
              "base_request": {
                "cost": 1,
                "sale": 2
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "27:gemini-2.5-flash-image",
      "channelId": 27,
      "channel": "Google Vertex AI - release-overseas",
      "channelPlatform": "Google Cloud Vertex AI",
      "region": "overseas",
      "model": "gemini-2.5-flash-image",
      "upstreamModel": "gemini-2.5-flash-image",
      "name": "Nano Banana",
      "maker": "Google",
      "modality": "image",
      "catalogCard": "Vertex AI·NanoBanana",
      "templateId": 23,
      "templateName": "Google Vertex AI - release-overseas 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 147,
          "category": "text2image",
          "label": "文生图",
          "protocol": "vertex-gemini",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "1K": {
                "cost": 28,
                "sale": 56
              },
              "base_request": {
                "cost": 1,
                "sale": 2
              }
            }
          }
        },
        {
          "id": 148,
          "category": "image2image",
          "label": "参考图生图",
          "protocol": "vertex-gemini",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "1K": {
                "cost": 28,
                "sale": 56
              },
              "input_image": {
                "cost": 1,
                "sale": 2
              },
              "base_request": {
                "cost": 1,
                "sale": 2
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "27:gemini-omni-1.1-flash-preview",
      "channelId": 27,
      "channel": "Google Vertex AI - release-overseas",
      "channelPlatform": "Google Cloud Vertex AI",
      "region": "overseas",
      "model": "gemini-omni-1.1-flash-preview",
      "upstreamModel": "gemini-omni-1.1-flash-preview",
      "name": "Gemini Omni 1.1 Flash（预览）",
      "maker": "Google",
      "modality": "video",
      "catalogCard": "Vertex AI·Gemini Omni",
      "templateId": 23,
      "templateName": "Google Vertex AI - release-overseas 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 149,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "vertex-gemini",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "4K": {
                "cost": 217,
                "sale": 434,
                "inCost": 0,
                "inSale": 0
              },
              "360P": {
                "cost": 24,
                "sale": 48,
                "inCost": 0,
                "inSale": 0
              },
              "720P": {
                "cost": 72,
                "sale": 144,
                "inCost": 0,
                "inSale": 0
              },
              "1080P": {
                "cost": 109,
                "sale": 218,
                "inCost": 0,
                "inSale": 0
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "27:veo-3.1-generate-001",
      "channelId": 27,
      "channel": "Google Vertex AI - release-overseas",
      "channelPlatform": "Google Cloud Vertex AI",
      "region": "overseas",
      "model": "veo-3.1-generate-001",
      "upstreamModel": "veo-3.1-generate-001",
      "name": "Veo 3.1",
      "maker": "Google",
      "modality": "video",
      "catalogCard": "Vertex AI·Veo 3.1",
      "templateId": 23,
      "templateName": "Google Vertex AI - release-overseas 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 150,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "vertex-veo",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "4K": {
                "cost": 429,
                "sale": 858,
                "inCost": 0,
                "inSale": 0
              },
              "720P": {
                "cost": 286,
                "sale": 572,
                "inCost": 0,
                "inSale": 0
              },
              "1080P": {
                "cost": 286,
                "sale": 572,
                "inCost": 0,
                "inSale": 0
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "27:veo-3.1-fast-generate-001",
      "channelId": 27,
      "channel": "Google Vertex AI - release-overseas",
      "channelPlatform": "Google Cloud Vertex AI",
      "region": "overseas",
      "model": "veo-3.1-fast-generate-001",
      "upstreamModel": "veo-3.1-fast-generate-001",
      "name": "Veo 3.1 Fast",
      "maker": "Google",
      "modality": "video",
      "catalogCard": "Vertex AI·Veo 3.1",
      "templateId": 23,
      "templateName": "Google Vertex AI - release-overseas 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 151,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "vertex-veo",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "720P": {
                "cost": 72,
                "sale": 144,
                "inCost": 0,
                "inSale": 0
              },
              "1080P": {
                "cost": 86,
                "sale": 172,
                "inCost": 0,
                "inSale": 0
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "27:veo-3.1-lite-generate-001",
      "channelId": 27,
      "channel": "Google Vertex AI - release-overseas",
      "channelPlatform": "Google Cloud Vertex AI",
      "region": "overseas",
      "model": "veo-3.1-lite-generate-001",
      "upstreamModel": "veo-3.1-lite-generate-001",
      "name": "Veo 3.1 Lite（预览）",
      "maker": "Google",
      "modality": "video",
      "catalogCard": "Vertex AI·Veo 3.1",
      "templateId": 23,
      "templateName": "Google Vertex AI - release-overseas 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 152,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "vertex-veo",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "720P": {
                "cost": 36,
                "sale": 72,
                "inCost": 0,
                "inSale": 0
              },
              "1080P": {
                "cost": 58,
                "sale": 116,
                "inCost": 0,
                "inSale": 0
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "27:gemini-3.1-flash-tts-preview",
      "channelId": 27,
      "channel": "Google Vertex AI - release-overseas",
      "channelPlatform": "Google Cloud Vertex AI",
      "region": "overseas",
      "model": "gemini-3.1-flash-tts-preview",
      "upstreamModel": "gemini-3.1-flash-tts-preview",
      "name": "Gemini 3.1 Flash TTS Preview",
      "maker": "Google",
      "modality": "audio",
      "catalogCard": "Vertex AI·Gemini TTS",
      "templateId": 23,
      "templateName": "Google Vertex AI - release-overseas 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 153,
          "category": "text2audio",
          "label": "语音生成",
          "protocol": "vertex-gemini-tts",
          "enabled": true,
          "price": {
            "cost": 180,
            "mode": "per_kchar",
            "sale": 360
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "27:gemini-2.5-flash-tts",
      "channelId": 27,
      "channel": "Google Vertex AI - release-overseas",
      "channelPlatform": "Google Cloud Vertex AI",
      "region": "overseas",
      "model": "gemini-2.5-flash-tts",
      "upstreamModel": "gemini-2.5-flash-tts",
      "name": "Gemini 2.5 Flash TTS",
      "maker": "Google",
      "modality": "audio",
      "catalogCard": "Vertex AI·Gemini TTS",
      "templateId": 23,
      "templateName": "Google Vertex AI - release-overseas 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 154,
          "category": "text2audio",
          "label": "语音生成",
          "protocol": "vertex-gemini-tts",
          "enabled": true,
          "price": {
            "cost": 90,
            "mode": "per_kchar",
            "sale": 180
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "27:gemini-2.5-flash-lite-preview-tts",
      "channelId": 27,
      "channel": "Google Vertex AI - release-overseas",
      "channelPlatform": "Google Cloud Vertex AI",
      "region": "overseas",
      "model": "gemini-2.5-flash-lite-preview-tts",
      "upstreamModel": "gemini-2.5-flash-lite-preview-tts",
      "name": "Gemini 2.5 Flash Lite Preview TTS",
      "maker": "Google",
      "modality": "audio",
      "catalogCard": "Vertex AI·Gemini TTS",
      "templateId": 23,
      "templateName": "Google Vertex AI - release-overseas 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 155,
          "category": "text2audio",
          "label": "语音生成",
          "protocol": "vertex-gemini-tts",
          "enabled": true,
          "price": {
            "cost": 90,
            "mode": "per_kchar",
            "sale": 180
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "27:gemini-2.5-pro-tts",
      "channelId": 27,
      "channel": "Google Vertex AI - release-overseas",
      "channelPlatform": "Google Cloud Vertex AI",
      "region": "overseas",
      "model": "gemini-2.5-pro-tts",
      "upstreamModel": "gemini-2.5-pro-tts",
      "name": "Gemini 2.5 Pro TTS",
      "maker": "Google",
      "modality": "audio",
      "catalogCard": "Vertex AI·Gemini TTS",
      "templateId": 23,
      "templateName": "Google Vertex AI - release-overseas 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 156,
          "category": "text2audio",
          "label": "语音生成",
          "protocol": "vertex-gemini-tts",
          "enabled": true,
          "price": {
            "cost": 180,
            "mode": "per_kchar",
            "sale": 360
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "28:seed-audio-1.0",
      "channelId": 28,
      "channel": "火山引擎豆包语音 Seed Audio",
      "channelPlatform": "火山引擎豆包语音",
      "region": "domestic",
      "model": "seed-audio-1.0",
      "upstreamModel": "seed-audio-1.0",
      "name": "Seed Audio 1.0",
      "maker": "字节跳动 / ByteDance",
      "modality": "audio",
      "catalogCard": "豆包·Seed Audio",
      "templateId": 24,
      "templateName": "火山引擎豆包语音 Seed Audio 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 158,
          "category": "text2audio",
          "label": "语音生成",
          "protocol": "doubao-seed-audio",
          "enabled": true,
          "price": {
            "cost": 30,
            "mode": "per_minute",
            "sale": 60
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "30:byteplus-seed-audio-1-0",
      "channelId": 30,
      "channel": "BytePlus Voice 新加坡（Seed Audio 1.0 / TTS 2.0）",
      "channelPlatform": "BytePlus Voice",
      "region": "overseas",
      "model": "byteplus-seed-audio-1-0",
      "upstreamModel": "seed-audio-1.0",
      "name": "Seed Audio 1.0 (BytePlus)",
      "maker": "字节跳动 / ByteDance",
      "modality": "audio",
      "catalogCard": "BytePlus·Seed Audio 1.0",
      "templateId": 25,
      "templateName": "BytePlus Voice 新加坡（Seed Audio 1.0 / TTS 2.0） 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 159,
          "category": "text2audio",
          "label": "语音生成",
          "protocol": "byteplus-seed-audio",
          "enabled": true,
          "price": {
            "cost": 108,
            "mode": "per_minute",
            "sale": 216
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "30:byteplus-seed-speech-tts-2-0",
      "channelId": 30,
      "channel": "BytePlus Voice 新加坡（Seed Audio 1.0 / TTS 2.0）",
      "channelPlatform": "BytePlus Voice",
      "region": "overseas",
      "model": "byteplus-seed-speech-tts-2-0",
      "upstreamModel": "seed-tts-2.0",
      "name": "Seed Speech TTS 2.0 (BytePlus)",
      "maker": "字节跳动 / ByteDance",
      "modality": "audio",
      "catalogCard": "BytePlus·Seed Speech TTS 2.0",
      "templateId": 25,
      "templateName": "BytePlus Voice 新加坡（Seed Audio 1.0 / TTS 2.0） 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 160,
          "category": "text2audio",
          "label": "语音生成",
          "protocol": "byteplus-seed-speech-tts",
          "enabled": true,
          "price": {
            "cost": 22,
            "mode": "per_kchar",
            "sale": 44
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "31:minimax-global-h3",
      "channelId": 31,
      "channel": "MiniMax Global",
      "channelPlatform": "MiniMax API Platform",
      "region": "overseas",
      "model": "minimax-global-h3",
      "upstreamModel": "MiniMax-H3",
      "name": "MiniMax H3 (Global)",
      "maker": "MiniMax",
      "modality": "video",
      "catalogCard": "MiniMax Global·H3",
      "templateId": 26,
      "templateName": "MiniMax Global 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 161,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "minimax-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "2K": {
                "cost": 93,
                "sale": 186,
                "inCost": 93,
                "inSale": 186
              },
              "768P": {
                "cost": 58,
                "sale": 116,
                "inCost": 58,
                "inSale": 116
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "31:minimax-global-hailuo-2-3",
      "channelId": 31,
      "channel": "MiniMax Global",
      "channelPlatform": "MiniMax API Platform",
      "region": "overseas",
      "model": "minimax-global-hailuo-2-3",
      "upstreamModel": "MiniMax-Hailuo-2.3",
      "name": "Hailuo 2.3 (Global)",
      "maker": "MiniMax",
      "modality": "video",
      "catalogCard": "MiniMax Global·Hailuo 2.3",
      "templateId": 26,
      "templateName": "MiniMax Global 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 162,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "minimax-v1-task",
          "enabled": true,
          "price": {
            "mode": "per_video",
            "tiers": {
              "768P-6s": {
                "cost": 200,
                "sale": 400
              },
              "1080P-6s": {
                "cost": 350,
                "sale": 700
              },
              "768P-10s": {
                "cost": 400,
                "sale": 800
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "32:bfl-flux-2-pro",
      "channelId": 32,
      "channel": "Black Forest Labs · FLUX.2 (Default)",
      "channelPlatform": "Black Forest Labs API",
      "region": "overseas",
      "model": "bfl-flux-2-pro",
      "upstreamModel": "flux-2-pro",
      "name": "FLUX.2 [pro]",
      "maker": "Black Forest Labs",
      "modality": "image",
      "catalogCard": "Black Forest Labs·FLUX.2",
      "templateId": 27,
      "templateName": "Black Forest Labs · FLUX.2 (Default) 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 163,
          "category": "text2image",
          "label": "文生图",
          "protocol": "bfl-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 86,
                "sale": 172
              }
            }
          }
        },
        {
          "id": 164,
          "category": "image2image",
          "label": "参考图生图",
          "protocol": "bfl-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 129,
                "sale": 258
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "32:bfl-flux-2-max",
      "channelId": 32,
      "channel": "Black Forest Labs · FLUX.2 (Default)",
      "channelPlatform": "Black Forest Labs API",
      "region": "overseas",
      "model": "bfl-flux-2-max",
      "upstreamModel": "flux-2-max",
      "name": "FLUX.2 [max]",
      "maker": "Black Forest Labs",
      "modality": "image",
      "catalogCard": "Black Forest Labs·FLUX.2",
      "templateId": 27,
      "templateName": "Black Forest Labs · FLUX.2 (Default) 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 165,
          "category": "text2image",
          "label": "文生图",
          "protocol": "bfl-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 200,
                "sale": 400
              }
            }
          }
        },
        {
          "id": 166,
          "category": "image2image",
          "label": "参考图生图",
          "protocol": "bfl-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 200,
                "sale": 400
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "32:bfl-flux-2-flex",
      "channelId": 32,
      "channel": "Black Forest Labs · FLUX.2 (Default)",
      "channelPlatform": "Black Forest Labs API",
      "region": "overseas",
      "model": "bfl-flux-2-flex",
      "upstreamModel": "flux-2-flex",
      "name": "FLUX.2 [flex]",
      "maker": "Black Forest Labs",
      "modality": "image",
      "catalogCard": "Black Forest Labs·FLUX.2",
      "templateId": 27,
      "templateName": "Black Forest Labs · FLUX.2 (Default) 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 167,
          "category": "text2image",
          "label": "文生图",
          "protocol": "bfl-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 143,
                "sale": 286
              }
            }
          }
        },
        {
          "id": 168,
          "category": "image2image",
          "label": "参考图生图",
          "protocol": "bfl-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 286,
                "sale": 572
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "32:bfl-flux-2-klein-9b",
      "channelId": 32,
      "channel": "Black Forest Labs · FLUX.2 (Default)",
      "channelPlatform": "Black Forest Labs API",
      "region": "overseas",
      "model": "bfl-flux-2-klein-9b",
      "upstreamModel": "flux-2-klein-9b",
      "name": "FLUX.2 [klein] 9B",
      "maker": "Black Forest Labs",
      "modality": "image",
      "catalogCard": "Black Forest Labs·FLUX.2",
      "templateId": 27,
      "templateName": "Black Forest Labs · FLUX.2 (Default) 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 169,
          "category": "text2image",
          "label": "文生图",
          "protocol": "bfl-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 15,
                "sale": 30
              }
            }
          }
        },
        {
          "id": 170,
          "category": "image2image",
          "label": "参考图生图",
          "protocol": "bfl-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 15,
                "sale": 30
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "32:bfl-flux-2-klein-4b",
      "channelId": 32,
      "channel": "Black Forest Labs · FLUX.2 (Default)",
      "channelPlatform": "Black Forest Labs API",
      "region": "overseas",
      "model": "bfl-flux-2-klein-4b",
      "upstreamModel": "flux-2-klein-4b",
      "name": "FLUX.2 [klein] 4B",
      "maker": "Black Forest Labs",
      "modality": "image",
      "catalogCard": "Black Forest Labs·FLUX.2",
      "templateId": 27,
      "templateName": "Black Forest Labs · FLUX.2 (Default) 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 171,
          "category": "text2image",
          "label": "文生图",
          "protocol": "bfl-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 13,
                "sale": 26
              }
            }
          }
        },
        {
          "id": 172,
          "category": "image2image",
          "label": "参考图生图",
          "protocol": "bfl-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "default": {
                "cost": 13,
                "sale": 26
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "32:bfl-flux-3-video",
      "channelId": 32,
      "channel": "Black Forest Labs · FLUX.2 (Default)",
      "channelPlatform": "Black Forest Labs API",
      "region": "overseas",
      "model": "bfl-flux-3-video",
      "upstreamModel": "flux-3-video",
      "name": "FLUX 3 Video",
      "maker": "Black Forest Labs",
      "modality": "video",
      "catalogCard": "Black Forest Labs·FLUX 3 Video",
      "templateId": 27,
      "templateName": "Black Forest Labs · FLUX.2 (Default) 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 173,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "bfl-video",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "720P": {
                "cost": 122,
                "sale": 244,
                "inCost": 0,
                "inSale": 0
              },
              "1080P": {
                "cost": 208,
                "sale": 416,
                "inCost": 0,
                "inSale": 0
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "35:xai-grok-imagine-image-2.0",
      "channelId": 35,
      "channel": "xAI（Grok Imagine 图片 / 视频）",
      "channelPlatform": "xAI API",
      "region": "overseas",
      "model": "xai-grok-imagine-image-2.0",
      "upstreamModel": "grok-imagine-image-2.0",
      "name": "Grok Imagine Image 2.0",
      "maker": "xAI",
      "modality": "image",
      "catalogCard": "xAI·Grok Imagine Image 2.0",
      "templateId": 28,
      "templateName": "xAI（Grok Imagine 图片 / 视频） 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 190,
          "category": "text2image",
          "label": "文生图",
          "protocol": "xai-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "1K": {
                "cost": 43,
                "sale": 86
              },
              "2K": {
                "cost": 58,
                "sale": 116
              }
            }
          }
        },
        {
          "id": 191,
          "category": "image2image",
          "label": "参考图生图",
          "protocol": "xai-image",
          "enabled": true,
          "price": {
            "mode": "per_image",
            "tiers": {
              "1K": {
                "cost": 43,
                "sale": 86
              },
              "2K": {
                "cost": 58,
                "sale": 116
              },
              "input_image": {
                "cost": 8,
                "sale": 16
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "35:xai-grok-imagine-video-1.5",
      "channelId": 35,
      "channel": "xAI（Grok Imagine 图片 / 视频）",
      "channelPlatform": "xAI API",
      "region": "overseas",
      "model": "xai-grok-imagine-video-1.5",
      "upstreamModel": "grok-imagine-video-1.5",
      "name": "Grok Imagine Video 1.5",
      "maker": "xAI",
      "modality": "video",
      "catalogCard": "xAI·Grok Imagine Video 1.5",
      "templateId": 28,
      "templateName": "xAI（Grok Imagine 图片 / 视频） 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 192,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "xai-video",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "480P": {
                "cost": 58,
                "sale": 116,
                "inCost": 0,
                "inSale": 0
              },
              "720P": {
                "cost": 100,
                "sale": 200,
                "inCost": 0,
                "inSale": 0
              },
              "1080P": {
                "cost": 179,
                "sale": 358,
                "inCost": 0,
                "inSale": 0
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "36:baidu-tts-large",
      "channelId": 36,
      "channel": "百度智能云（大模型语音合成）",
      "channelPlatform": "百度智能云语音",
      "region": "domestic",
      "model": "baidu-tts-large",
      "upstreamModel": "baidu-tts-large",
      "name": "百度大模型语音合成",
      "maker": "百度",
      "modality": "audio",
      "catalogCard": "百度智能云·大模型语音合成",
      "templateId": 29,
      "templateName": "百度智能云（大模型语音合成） 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 193,
          "category": "text2audio",
          "label": "语音生成",
          "protocol": "baidu-tts",
          "enabled": true,
          "price": {
            "cost": 0.45,
            "mode": "per_call",
            "sale": 1
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "37:ernie-4.5-turbo-32k",
      "channelId": 37,
      "channel": "百度智能云·千帆文本",
      "channelPlatform": "百度智能云千帆",
      "region": "domestic",
      "model": "ernie-4.5-turbo-32k",
      "upstreamModel": "ernie-4.5-turbo-32k",
      "name": "ERNIE 4.5 Turbo 32K",
      "maker": "百度",
      "modality": "text",
      "catalogCard": "百度智能云·千帆文本",
      "templateId": 30,
      "templateName": "百度智能云·千帆文本 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 194,
          "category": "text2text",
          "label": "文本生成",
          "protocol": "baidu-qianfan-chat",
          "enabled": true,
          "price": {
            "mode": "token",
            "costIn": 80,
            "saleIn": 160,
            "costOut": 320,
            "saleOut": 640
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "38:wan3.0-video",
      "channelId": 38,
      "channel": "Alibaba Model Studio SG",
      "channelPlatform": "Alibaba Cloud Model Studio",
      "region": "overseas",
      "model": "wan3.0-video",
      "upstreamModel": "wan3.0-video",
      "name": "Wan 3.0 (Standard)",
      "maker": "阿里云 / Alibaba Cloud",
      "modality": "video",
      "catalogCard": "Alibaba Cloud Model Studio·Wan 3.0",
      "templateId": 31,
      "templateName": "Alibaba Model Studio SG 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 195,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "dashscope-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "480P": {
                "cost": 34,
                "sale": 68,
                "inCost": 34,
                "inSale": 68
              },
              "720P": {
                "cost": 67,
                "sale": 134,
                "inCost": 67,
                "inSale": 134
              },
              "1080P": {
                "cost": 134,
                "sale": 268,
                "inCost": 134,
                "inSale": 268
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "38:wan3.0-video-prime",
      "channelId": 38,
      "channel": "Alibaba Model Studio SG",
      "channelPlatform": "Alibaba Cloud Model Studio",
      "region": "overseas",
      "model": "wan3.0-video-prime",
      "upstreamModel": "wan3.0-video-prime",
      "name": "Wan 3.0 Prime (优速版)",
      "maker": "阿里云 / Alibaba Cloud",
      "modality": "video",
      "catalogCard": "Alibaba Cloud Model Studio·Wan 3.0",
      "templateId": 31,
      "templateName": "Alibaba Model Studio SG 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 196,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "dashscope-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "480P": {
                "cost": 46,
                "sale": 92,
                "inCost": 46,
                "inSale": 92
              },
              "720P": {
                "cost": 94,
                "sale": 188,
                "inCost": 94,
                "inSale": 188
              },
              "1080P": {
                "cost": 188,
                "sale": 376,
                "inCost": 188,
                "inSale": 376
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "38:happyhorse-1.1-t2v",
      "channelId": 38,
      "channel": "Alibaba Model Studio SG",
      "channelPlatform": "Alibaba Cloud Model Studio",
      "region": "overseas",
      "model": "happyhorse-1.1-t2v",
      "upstreamModel": "happyhorse-1.1-t2v",
      "name": "Happy Horse 1.1",
      "maker": "阿里云 / Alibaba Cloud",
      "modality": "video",
      "catalogCard": "Alibaba Cloud Model Studio·HappyHorse",
      "templateId": 31,
      "templateName": "Alibaba Model Studio SG 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 197,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "dashscope-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "480P": {
                "cost": 47,
                "sale": 94,
                "inCost": 0,
                "inSale": 0
              },
              "720P": {
                "cost": 94,
                "sale": 188,
                "inCost": 0,
                "inSale": 0
              },
              "1080P": {
                "cost": 121,
                "sale": 242,
                "inCost": 0,
                "inSale": 0
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "38:happyhorse-1.1-i2v",
      "channelId": 38,
      "channel": "Alibaba Model Studio SG",
      "channelPlatform": "Alibaba Cloud Model Studio",
      "region": "overseas",
      "model": "happyhorse-1.1-i2v",
      "upstreamModel": "happyhorse-1.1-i2v",
      "name": "Happy Horse 1.1 (首帧图生)",
      "maker": "阿里云 / Alibaba Cloud",
      "modality": "video",
      "catalogCard": "Alibaba Cloud Model Studio·HappyHorse",
      "templateId": 31,
      "templateName": "Alibaba Model Studio SG 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 198,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "dashscope-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "480P": {
                "cost": 47,
                "sale": 94,
                "inCost": 0,
                "inSale": 0
              },
              "720P": {
                "cost": 94,
                "sale": 188,
                "inCost": 0,
                "inSale": 0
              },
              "1080P": {
                "cost": 121,
                "sale": 242,
                "inCost": 0,
                "inSale": 0
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "38:happyhorse-1.1-r2v",
      "channelId": 38,
      "channel": "Alibaba Model Studio SG",
      "channelPlatform": "Alibaba Cloud Model Studio",
      "region": "overseas",
      "model": "happyhorse-1.1-r2v",
      "upstreamModel": "happyhorse-1.1-r2v",
      "name": "Happy Horse 1.1 (参考图生)",
      "maker": "阿里云 / Alibaba Cloud",
      "modality": "video",
      "catalogCard": "Alibaba Cloud Model Studio·HappyHorse",
      "templateId": 31,
      "templateName": "Alibaba Model Studio SG 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 199,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "dashscope-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "480P": {
                "cost": 47,
                "sale": 94,
                "inCost": 0,
                "inSale": 0
              },
              "720P": {
                "cost": 94,
                "sale": 188,
                "inCost": 0,
                "inSale": 0
              },
              "1080P": {
                "cost": 121,
                "sale": 242,
                "inCost": 0,
                "inSale": 0
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "38:happyhorse-1.0-t2v",
      "channelId": 38,
      "channel": "Alibaba Model Studio SG",
      "channelPlatform": "Alibaba Cloud Model Studio",
      "region": "overseas",
      "model": "happyhorse-1.0-t2v",
      "upstreamModel": "happyhorse-1.0-t2v",
      "name": "Happy Horse 1.0",
      "maker": "阿里云 / Alibaba Cloud",
      "modality": "video",
      "catalogCard": "Alibaba Cloud Model Studio·HappyHorse",
      "templateId": 31,
      "templateName": "Alibaba Model Studio SG 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 200,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "dashscope-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "720P": {
                "cost": 94,
                "sale": 188,
                "inCost": 0,
                "inSale": 0
              },
              "1080P": {
                "cost": 161,
                "sale": 322,
                "inCost": 0,
                "inSale": 0
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "38:happyhorse-1.0-i2v",
      "channelId": 38,
      "channel": "Alibaba Model Studio SG",
      "channelPlatform": "Alibaba Cloud Model Studio",
      "region": "overseas",
      "model": "happyhorse-1.0-i2v",
      "upstreamModel": "happyhorse-1.0-i2v",
      "name": "Happy Horse 1.0 (首帧图生)",
      "maker": "阿里云 / Alibaba Cloud",
      "modality": "video",
      "catalogCard": "Alibaba Cloud Model Studio·HappyHorse",
      "templateId": 31,
      "templateName": "Alibaba Model Studio SG 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 201,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "dashscope-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "720P": {
                "cost": 94,
                "sale": 188,
                "inCost": 0,
                "inSale": 0
              },
              "1080P": {
                "cost": 161,
                "sale": 322,
                "inCost": 0,
                "inSale": 0
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "38:happyhorse-1.0-r2v",
      "channelId": 38,
      "channel": "Alibaba Model Studio SG",
      "channelPlatform": "Alibaba Cloud Model Studio",
      "region": "overseas",
      "model": "happyhorse-1.0-r2v",
      "upstreamModel": "happyhorse-1.0-r2v",
      "name": "Happy Horse 1.0 (参考图生)",
      "maker": "阿里云 / Alibaba Cloud",
      "modality": "video",
      "catalogCard": "Alibaba Cloud Model Studio·HappyHorse",
      "templateId": 31,
      "templateName": "Alibaba Model Studio SG 计费模板",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 202,
          "category": "text2video",
          "label": "视频生成",
          "protocol": "dashscope-task",
          "enabled": true,
          "price": {
            "mode": "per_second",
            "tiers": {
              "720P": {
                "cost": 94,
                "sale": 188,
                "inCost": 0,
                "inSale": 0
              },
              "1080P": {
                "cost": 161,
                "sale": 322,
                "inCost": 0,
                "inSale": 0
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    },
    {
      "id": "39:byteplus-mediakit",
      "channelId": 39,
      "channel": "BytePlus AI MediaKit 新加坡",
      "channelPlatform": "BytePlus AI MediaKit",
      "region": "overseas",
      "model": "byteplus-mediakit",
      "upstreamModel": "byteplus-mediakit",
      "name": "BytePlus AI MediaKit 图片处理",
      "maker": "字节跳动 / ByteDance",
      "modality": "image",
      "catalogCard": "BytePlus·AI MediaKit（图片）",
      "templateId": 0,
      "templateName": "",
      "channelEnabled": true,
      "abilities": [
        {
          "id": 203,
          "category": "image_func",
          "label": "图片工具",
          "protocol": "byteplus-mediakit",
          "enabled": true,
          "price": {
            "mode": "functions",
            "items": {
              "图片高清#0": {
                "cost": 4.32,
                "sale": 8.64
              }
            }
          }
        },
        {
          "id": 204,
          "category": "video_func",
          "label": "视频工具",
          "protocol": "byteplus-mediakit",
          "enabled": true,
          "price": {
            "mode": "functions",
            "items": {
              "人声分离#0": {
                "cost": 7.2,
                "sale": 14.4
              }
            }
          }
        }
      ],
      "updatedAt": "2026-09-23 11:35:37",
      "enabled": true,
      "pricingComplete": true
    }
  ]
};
